name: deployment
on:
  push:
    branches:
      - master

jobs:
  build-n-publish:
    name: Build and publish Python ðŸ distributions ðŸ“¦ to PyPI and TestPyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Installing wheel 
      run: pip install wheel twine
    - name: Build a binary wheel and a source tarball
      run: python3 setup.py sdist bdist_wheel
    - name: Publish distribution ðŸ“¦ to Test PyPI
      run: >-
        twine upload --repository-url https://test.pypi.org/legacy/ dist/* 
        --skip-existing 
        -p ${{ secrets.test_pypi_api_key }}
        -u __token__
    - name: Publish distribution ðŸ“¦ to PyPI
      run: >-
        twine upload dist/*
        --skip-existing 
        -p ${{ secrets.pypi_api_key }}
        -u __token__
